### ISSUE TITLE
wiseflow-core-1 exited building成功，running失败

### ISSUE THREAD

**Issue by death4444** [TeamWiseFlow/wiseflow#12]
![image](https://github.com/TeamWiseFlow/wiseflow/assets/26320543/f0fe1b68-bb65-441a-9c57-60b7f88edc31)
    sock = socket.create_connection(

  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection

    raise err

  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions

    yield

  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request

    resp = self._pool.handle_request(req)

  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request

    raise exc

  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request

    response = connection.handle_request(request)

  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 92, in handle_request

    raise exc

  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 69, in handle_request

    stream = self._connect(request)

  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 117, in _connect

    stream = self._network_backend.connect_tcp(**kwargs)

  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 99, in connect_tcp

    with map_exceptions(exc_map):

  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions

    raise to_exc(exc) from exc

httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 95, in _send

    response = self.http_client.request(

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request

    return self.send(request, auth=auth, follow_redirects=follow_redirects)

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send

    response = self._send_handling_auth(

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth

    response = self._send_handling_redirects(

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects

    response = self._send_single_request(request)

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request

    response = transport.handle_request(request)

  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request

    with map_httpcore_exceptions():

  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions

    raise mapped_exc(message) from exc

httpx.ConnectError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap

    self.run()

  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started

    target(sockets=sockets)

  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run

    return asyncio.run(self.serve(sockets=sockets))

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete

  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve

    await self._serve(sockets)

  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve

    config.load()

  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load

    self.loaded_app = import_from_string(self.app)

  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string

    module = importlib.import_module(module_str)

  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/app/backend.py", line 5, in <module>

    from insights import message_manager

  File "/app/insights/__init__.py", line 5, in <module>

    from .get_info import get_info, pb, project_dir, logger, info_rewrite

  File "/app/insights/get_info.py", line 27, in <module>

    pb = PbTalker(logger)

  File "/app/utils/pb_api.py", line 24, in __init__

    user_data = self.client.collection("users").auth_with_password(email, password)

  File "/usr/local/lib/python3.10/site-packages/pocketbase/services/record_service.py", line 173, in auth_with_password

    response_data = self.client.send(

  File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 119, in send

    response = self._send(path, req_config)

  File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 106, in _send

    raise ClientResponseError(

pocketbase.utils.ClientResponseError: General request error. Original error: [Errno 111] Connection refused
![image](https://github.com/TeamWiseFlow/wiseflow/assets/26320543/34ec203c-c048-4811-8598-07ec4d306af2)

**Comment by wwz223** [comment]
@death4444 看看是不是没有使用pb默认的地址 http://127.0.0.1:8090， 是的话，需要在env中配置正确的pb地址

**Comment by death4444** [comment]
> @death4444 看看是不是没有使用pb默认的地址 [http://127.0.0.1:8090，](http://127.0.0.1:8090%EF%BC%8C) 是的话，需要在env中配置正确的pb地址

我专门把这个8090端口号让出来的，之前被其他应用占了，但还是跑不起来

**Comment by bigbrother666sh** [comment]
打开 http://127.0.0.1:8090/_/  设定用户名和密码，然后用户名密码配置到.env里面

**Comment by wwz-wyze** [comment]
@death4444 如果你的端口是8090，需要在.env 中需要配置export "PB_API_BASE"="http://127.0.0.1:8090" 或者将 export "PB_API_BASE" = "" 注释掉
