### ISSUE TITLE
报错无法启动和登录pocketbase

### ISSUE THREAD

**Issue by zhstbj** [TeamWiseFlow/wiseflow#161]
报错如下，然后选择点击那个登录127.0.0.1的地址也没有反应，请问问题在哪，怎么解决？
![4d8a8c8d745ade0be9af0fd4fa65ec9](https://github.com/user-attachments/assets/cbad038f-b40d-4147-8f2c-25387b900f3c)
![4983cb2937159b3a155140244a0a9ab](https://github.com/user-attachments/assets/a8743cfb-8be1-46c8-af6c-f5b8a5da27d7)

**Comment by qwert1887** [comment]
一样

**Comment by zhstbj** [comment]
求教下哪位大神能帮忙看下给下解决方案或者思路🧐，谢谢

**Comment by qwert1887** [comment]
我昨天用最新的pocketbase和最新master的代码弄好了

**Comment by ourines** [comment]
仔细读一下 readme

**Comment by zhstbj** [comment]
> 仔细读一下 readme

不好意思，我确实仔细看了，也按照要求改了相关配置，比如.env文件，能具体解释下问题出在哪里么，之前的0.3.1版本也是类似的报错，再之前是能用的，后来不知道哪里操作错了还是咋了，就变成这样了。

**Comment by zhstbj** [comment]
之前的0.31版本报错如下：
core-1  | 2024/12/22 11:44:31 Server started at http://0.0.0.0:8090
core-1  | ├─ REST API: http://0.0.0.0:8090/api/
core-1  | └─ Admin UI: http://0.0.0.0:8090/_/
core-1  | 2024-12-22 11:44:33.548 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: http://127.0.0.1:8090
core-1  | Traceback (most recent call last):
core-1  |   File "/app/utils/pb_api.py", line 20, in __init__
core-1  |     admin_data = self.client.admins.auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/admin_service.py", line 90, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 116, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.errors.ClientResponseError: Response error. Status code:404
core-1  |
core-1  | During handling of the above exception, another exception occurred:
core-1  |
core-1  | Traceback (most recent call last):
core-1  |   File "/app/tasks.py", line 2, in <module>
core-1  |     from insights import pipeline, pb, logger
core-1  |   File "/app/insights/__init__.py", line 5, in <module>
core-1  |     from .get_info import get_info, pb, project_dir, logger, info_rewrite
core-1  |   File "/app/insights/get_info.py", line 26, in <module>
core-1  |     pb = PbTalker(logger)
core-1  |   File "/app/utils/pb_api.py", line 24, in __init__
core-1  |     user_data = self.client.collection("users").auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/record_service.py", line 218, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 116, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.errors.ClientResponseError: Response error. Status code:400
core-1  | 2024-12-22 11:44:33.904 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: http://127.0.0.1:8090
core-1  | Process SpawnProcess-1:
core-1  | Traceback (most recent call last):
core-1  |   File "/app/utils/pb_api.py", line 20, in __init__
core-1  |     admin_data = self.client.admins.auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/admin_service.py", line 90, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 116, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.errors.ClientResponseError: Response error. Status code:404
core-1  |
core-1  | During handling of the above exception, another exception occurred:
core-1  |
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
core-1  |     self.run()
core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
core-1  |     self._target(*self._args, **self._kwargs)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
core-1  |     target(sockets=sockets)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
core-1  |     return asyncio.run(self.serve(sockets=sockets))
core-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
core-1  |     return loop.run_until_complete(main)
core-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
core-1  |     return future.result()
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 70, in serve
core-1  |     await self._serve(sockets)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 77, in _serve
core-1  |     config.load()
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 435, in load
core-1  |     self.loaded_app = import_from_string(self.app)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
core-1  |     module = importlib.import_module(module_str)
core-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
core-1  |     return _bootstrap._gcd_import(name[level:], package, level)
core-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
core-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
core-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
core-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
core-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
core-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
core-1  |   File "/app/backend.py", line 5, in <module>
core-1  |     from insights import message_manager
core-1  |   File "/app/insights/__init__.py", line 5, in <module>
core-1  |     from .get_info import get_info, pb, project_dir, logger, info_rewrite
core-1  |   File "/app/insights/get_info.py", line 26, in <module>
core-1  |     pb = PbTalker(logger)
core-1  |   File "/app/utils/pb_api.py", line 24, in __init__
core-1  |     user_data = self.client.collection("users").auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/record_service.py", line 218, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 116, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.errors.ClientResponseError: Response error. Status code:400

**Comment by bigbrother666sh** [comment]
删除现在的代码文件，重新拉取
