### ISSUE TITLE
执行./run.sh脚本报错

### ISSUE THREAD

**Issue by BearGuo1** [TeamWiseFlow/wiseflow#166]
Macos M3，使用的conda最新版本
现在执行./run.sh脚本会遇到如下的报错，应该怎么解决

(wiseflow) ➜  core ./run.sh
.env: line 5: unexpected EOF while looking for matching `"'
.env: line 6: syntax error: unexpected end of file
PocketBase is already running.
Traceback (most recent call last):
  File "/Users/bear/Desktop/wiseflow-master 2/core/general_process.py", line 22, in <module>
    wiseflow_logger = get_logger('general_process', project_dir)
  File "/Users/bear/Desktop/wiseflow-master 2/core/utils/general_utils.py", line 83, in get_logger
    os.makedirs(logger_file_path)
  File "/Users/bear/anaconda3/envs/wiseflow/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
(wiseflow) ➜  core

**Comment by bigbrother666sh** [comment]
看起来是你的.env 文件第五行少了一个"? 或者多了一个 `， 可以参考代码仓的 env_sample 重新编辑

**Comment by BearGuo1** [comment]
确实是多了一个"的问题
