### ISSUE TITLE
run.sh后直接报错

### ISSUE THREAD

**Issue by oulihua7531681** [TeamWiseFlow/wiseflow#168]
Traceback (most recent call last):
File "C:\Users\Administrator\wiseflow\core\general_process.py", line 2, in <module>
from utils.pb_api import PbTalker
File "C:\Users\Administrator\wiseflow\core\utils\pb_api.py", line 2, in <module>
from pocketbase import PocketBase  # Client also works the same
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pocketbase'

pocketbase是正常的,
最新版的，在根目录的pb和core下也复制了一个pb，重新电脑后让run.sh自动高起，还是报数据库这块的的错误。

**Comment by bigbrother666sh** [comment]
进 core中执行 pip install -r requirements.txt

**Comment by oulihua7531681** [comment]
好的
