### ISSUE TITLE
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

### ISSUE THREAD

**Issue by Awakcn** [TeamWiseFlow/wiseflow#37]
这是什么情况，.env已经配置了siliconflow的LLM_API_KEY和LLM_API_BASE

2024-08-08 11:41:58 core-1  | 2024/08/08 03:41:58 Server started at http://0.0.0.0:8090
2024-08-08 11:41:58 core-1  | ├─ REST API: http://0.0.0.0:8090/api/
2024-08-08 11:41:58 core-1  | └─ Admin UI: http://0.0.0.0:8090/_/
2024-08-08 11:41:58 core-1  | Traceback (most recent call last):
2024-08-08 11:41:58 core-1  |   File "/app/tasks.py", line 2, in <module>
2024-08-08 11:41:58 core-1  |     from insights import pipeline, pb, logger
2024-08-08 11:41:58 core-1  |   File "/app/insights/__init__.py", line 3, in <module>
2024-08-08 11:41:58 core-1  |     from scrapers.general_crawler import general_crawler
2024-08-08 11:41:58 core-1  |   File "/app/scrapers/general_crawler.py", line 14, in <module>
2024-08-08 11:41:58 core-1  |     from llms.openai_wrapper import openai_llm
2024-08-08 11:41:58 core-1  |   File "/app/llms/openai_wrapper.py", line 11, in <module>
2024-08-08 11:41:58 core-1  |     client = OpenAI(base_url=base_url)
2024-08-08 11:41:58 core-1  |   File "/usr/local/lib/python3.10/site-packages/openai/_client.py", line 105, in __init__
2024-08-08 11:41:58 core-1  |     raise OpenAIError(
2024-08-08 11:41:58 core-1  | openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
2024-08-08 11:41:59 core-1  | Process SpawnProcess-1:
2024-08-08 11:41:59 core-1  | Traceback (most recent call last):
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-08-08 11:41:59 core-1  |     self.run()
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-08-08 11:41:59 core-1  |     self._target(*self._args, **self._kwargs)
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
2024-08-08 11:41:59 core-1  |     target(sockets=sockets)
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
2024-08-08 11:41:59 core-1  |     return asyncio.run(self.serve(sockets=sockets))
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2024-08-08 11:41:59 core-1  |     return loop.run_until_complete(main)
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-08-08 11:41:59 core-1  |     return future.result()
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
2024-08-08 11:41:59 core-1  |     await self._serve(sockets)
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
2024-08-08 11:41:59 core-1  |     config.load()
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
2024-08-08 11:41:59 core-1  |     self.loaded_app = import_from_string(self.app)
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
2024-08-08 11:41:59 core-1  |     module = importlib.import_module(module_str)
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-08-08 11:41:59 core-1  |     return _bootstrap._gcd_import(name[level:], package, level)
2024-08-08 11:41:59 core-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-08-08 11:41:59 core-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-08-08 11:41:59 core-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-08-08 11:41:59 core-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-08-08 11:41:59 core-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-08-08 11:41:59 core-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-08-08 11:41:59 core-1  |   File "/app/backend.py", line 5, in <module>
2024-08-08 11:41:59 core-1  |     from insights import message_manager
2024-08-08 11:41:59 core-1  |   File "/app/insights/__init__.py", line 3, in <module>
2024-08-08 11:41:59 core-1  |     from scrapers.general_crawler import general_crawler
2024-08-08 11:41:59 core-1  |   File "/app/scrapers/general_crawler.py", line 14, in <module>
2024-08-08 11:41:59 core-1  |     from llms.openai_wrapper import openai_llm
2024-08-08 11:41:59 core-1  |   File "/app/llms/openai_wrapper.py", line 11, in <module>
2024-08-08 11:41:59 core-1  |     client = OpenAI(base_url=base_url)
2024-08-08 11:41:59 core-1  |   File "/usr/local/lib/python3.10/site-packages/openai/_client.py", line 105, in __init__
2024-08-08 11:41:59 core-1  |     raise OpenAIError(
2024-08-08 11:41:59 core-1  | openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by Awakcn** [comment]
![image](https://github.com/user-attachments/assets/1e8e6cca-eb4d-4534-81d4-21996f7532e9)

**Comment by Awakcn** [comment]
![image](https://github.com/user-attachments/assets/6ff6efcf-0ee0-4966-8291-4874b52a578a)

**Comment by Awakcn** [comment]
是.env改完没有重新compose
